sudo: required
language: generic

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME="exercism-coq"
  - COQ_IMAGE="coqorg/coq:8.9"

install: |
  # Prepare the COQ container
  docker pull ${COQ_IMAGE}
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} ${COQ_IMAGE}

script:
  - |
    docker exec COQ /bin/bash --login -c "
      export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
      set -ex
      sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
      # coq_makefile -f _CoqProject -o Makefile
      # ( make && make install )
      bin/fetch-configlet
      bin/configlet lint .
      echo \"Docker run successful!\"
      " script
  - docker stop COQ
