sudo: false

addons:
  apt:
    sources:
    - sourceline: 'ppa:jgross-h/many-coq-versions'
    packages:
    - coq-8.6

before_install:
- coqc --version
- export PATH="${TRAVIS_BUILD_DIR}/bin:$PATH" # For {,fetch-}configlet.

install:
- fetch-configlet

script: 
- |
    set -e
    configlet .
    for exercise in ${TRAVIS_BUILD_DIR}/exercises/*/ ; do
        (cd $exercise; coqc example.v)
    done
